import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "500",
  style: "italic",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export default function RootLayout({ children }) {
  // console.log('hello world');  
  return (
    <html lang="en" className="m-10">
      <body
        className={`${poppins.className}  antialiased`}
      >
        <nav className="text-xl">
          <ul className="flex gap-4">
            <li><Link href='/'>Home</Link></li>
            <li><Link href='/about'>About</Link></li>
            <li><Link href='/blogs'>Blogs</Link></li>
            <li><Link href='/posts'>Posts</Link></li>
          </ul>
        </nav>
        <hr />
        {children}
      </body>
    </html>
  );
}
